language: R
sudo: required
dist: trusty

r_binary_packages:
 - rgeos
 - rjags

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-dev

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
